include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    sort_constructors_first: ignore
  exclude:
    - lib/l10n/generated/*
    - lib/generated/*
    - lib/**/*.g.dart
    - assets/**/*.gen.dart
    - packages/**/*.gen.dart
linter:
  rules:
    public_member_api_docs: false