name: storage
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dev_dependencies:
  build_runner: ^2.4.13
  mockito: ^5.4.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
