name: firebase_authentication_client
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  authentication_client:
    path: ../authentication_client
  firebase_auth: ^5.3.1
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  token_storage:
    path: ../token_storage

dev_dependencies:
  build_runner: ^2.4.13
  firebase_auth_mocks: ^0.14.1
  flutter_test:
    sdk: flutter
  google_sign_in_mocks: ^0.3.0
  mockito: ^5.4.4
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
